import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased text-white`}
      >

        {/* haeder navbar with tailwind*/}
        <header className="flex items-center justify-between p-4 bg-gray-800 text-white">
          <h1 className="text-2xl">ScamShield</h1>
          <nav>
            <ul className="flex gap-4">
              <li><a href="/">Home</a></li>
              <li><a href="/blacklist">Blacklist</a></li>
              <li><a href="/about-us">About</a></li>
              <li><a href="/tips">Tips </a></li>
            </ul>
          </nav>
        </header>

        <div className="mx-auto max-w-5xl">
          {children}
        </div>
        <section className="cta-section bg-blue-50 text-center p-6 sm:p-12">
          <h2 className="text-3xl sm:text-4xl font-bold text-blue-600 mb-4">
            Ready to Protect Your Online Experience?
          </h2>
          <p className="text-lg sm:text-xl text-gray-700 mb-6 max-w-3xl mx-auto">
            Join thousands of users who trust ScamShield to detect scams and safeguard their digital journey.
            It’s fast, reliable, and designed with your security in mind.
          </p>
          <a href="/" className="px-8 py-4 text-lg text-white bg-blue-500 rounded-md hover:bg-blue-600 focus:outline-none focus:ring-2 focus:ring-blue-500">
            Scan Your First URL
          </a>
        </section>

      </body>
    </html>
  );
}
