# Generated by Django 5.1.3 on 2024-12-01 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blacklist',
            name='reason',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
