# Generated by Django 5.1.3 on 2024-12-01 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0002_blacklist_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='blacklist',
            name='domain',
            field=models.CharField(default=' ', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blacklist',
            name='url',
            field=models.URLField(max_length=1000),
        ),
    ]
