# Generated by Django 5.1.3 on 2025-01-11 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0004_blacklistremovalrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scanreport',
            name='is_scam',
        ),
        migrations.AddField(
            model_name='scanreport',
            name='report',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scanreport',
            name='trust_score',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
