# Generated by Django 5.1.3 on 2025-01-11 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0005_remove_scanreport_is_scam_scanreport_report_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blacklist',
            name='message',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
